version: '3.8'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile.main
    image: wsr123/main-service:latest
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
      - FLASK_APP=app.py
    depends_on:
      - redis

  auth:
    build:
      context: .
      dockerfile: Dockerfile.auth
    image: wsr123/auth-service:latest
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
      - FLASK_APP=app.py
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  redis-data:
