ARG PYTHON_VERSION=3.8
FROM python:${PYTHON_VERSION}-slim as base

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV DATABASE_PATH=/app/data/urls.db
ENV FLASK_APP=auth.py

EXPOSE 8000

CMD ["python", "main.py", "--host=0.0.0.0", "--port=8000"]
