ARG PYTHON_VERSION=3.8
FROM python:${PYTHON_VERSION}-slim as base

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt ./

RUN python -m pip install --no-cache-dir -r requirements.txt

COPY . .

ENV DATABASE_PATH=/app/data/users.db
ENV FLASK_APP=auth.py

EXPOSE 8001

CMD ["python", "auth.py", "--host=0.0.0.0", "--port=8001"]
