apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url
  template:
    metadata:
      labels:
        app: url
    spec:
      containers:
      - name: url
        image: wsr123/main-service:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: url-db-volume
          mountPath: /app/data
      volumes:
      - name: url-db-volume
        persistentVolumeClaim:
          claimName: pvc-test
---
apiVersion: v1
kind: Service
metadata:
  name: url-service
spec:
  type: NodePort
  selector:
    app: url
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000




